- colors/onedark.vim
With this color definitions a commit file will look like this:
I use the same color bindings from solarized theme, but with this scheme colors.
> Add colors for git comment files

- colors/onedark.vim
Turns out it was pretty simple :)
Fix #21
> Apply the comment color to git commit messages

- colors/onedark.vim
Sorry for the PR spam :)
Test: https://github.com/caleb/gruvbox-syntax-atom/blob/master/spec/html.html
**Atom**
**Vim**
> Add HTML syntax highlighting

- colors/onedark.vim
This makes it bit easier to see the current search target
> Improve visibility of incsearch

- colors/onedark.vim
This tweaks a couple of the base colours and I also added some additional colours provided by the [vim-javascript](https://github.com/pangloss/vim-javascript) package. It seems one of the most popular and is included in [polyglot](https://github.com/sheerun/vim-polyglot). I also added some colours for [yajs](https://github.com/othree/yajs.vim) as that seems the other popular choice.
**Atom** 
**Vim** (standard)
**Vim** (pangloss)
**Vim** (yajs)
Also, here is the jQuery source screenshot:
**Atom**
**Vim** (standard)
**Vim** (pangloss)
Personally I think Atom is a bit overkill with the way it throws reds and blues together and I think the Vim version is much easier on the eyes
> Tweak JavaScript highlighting

- colors/onedark.vim
Makes it easier to spot errors at a glance:
**Atom**
**Vim**
**Neovim**
Usage of `reverse` taken from - http://vi.stackexchange.com/questions/3288/override-cursorline-background-color-by-syntax-highlighting
> Add highlighting of JSON errors

- colors/onedark.vim
Before:
After:
EDIT: changed screenshot
> Improved JSDoc Colors in YAJS

- colors/onedark.vim
This makes large lists of directories and files a little easier to scan
Fixes #42
> Fix colours for NERDTree

- colors/onedark.vim
This works correctly in vanilla Vim but with polyglot they show up white. Figured no harm in being explicit
> Add colour for JSON boolean and number

- colors/onedark.vim
Allows errors and warnings to stand out:
Before:
After:
> Add colour to Neomake signs

- colors/onedark.vim
Uses https://github.com/leafgarland/typescript-vim from polyglot. Only some minor tweaks to match normal JS as not much syntax is provided
> Add some tweaks for TypeScript

- build/templates/onedark.template.vim
- colors/onedark.vim
vim-polyglot has removed the sass syntax highlighting in favour of a [third party scss version](https://github.com/sheerun/vim-polyglot/pull/173). This tweaks a few colours to keep it consistent.
It offers less control over colours unfortunately but it looks acceptable next to One Dark in Atom.
> Update Sass syntax highlighting

- build/templates/onedark.template.vim
- colors/onedark.vim
> Updated git commit color so header overflow is red

- colors/onedark.vim
Seems few days ago was introduced a new option for highlight.
Now [QuickFixLine](https://github.com/vim/vim/search?utf8=%E2%9C%93&q=QuickFixLine&type=) is responsible for setting the color for the current
line in Quickfix list.
Before the fixing:
After the fixing:
Vim don't throw any exception for invalid keys used in `call s:h("key_group", ...)`. So it shouldn't affect the users that still using the previous versions.
My VIM version: `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 12 2017 08:56:45)`
> Fix quickfix current line

- README.md
- colors/onedark.vim
Hi,
I really like this color scheme, but i miss bold font. I like to use it for functions, statements, etc.
I tried using `onedark#set_highlight`, but that requires you to pass in whole highlight dictionary, where i wanted only to append `gui=bold` to some parts.
I added `onedark#extend_highlight` which will use vimscript native `extend()` function to change certain highlight option within a highlight group. So with this, i can easily extend my highlight group to be bold like this:
```vim
call onedark#extend_highlight("Function", { "gui": "bold" })
```
> Expose function for extending highlight group.

- colors/onedark.vim
In the fish shell, the keyword 'end' is used both as a keyword and for
ending conditional logic.
For example, in the trivial function below, the word `end` is used to
terminate the "if" conditional, and it's also used as a keyword to
indicate the end of the function.
This tweak makes the word the same color in both places. I selected
purple to match the Onedark scheme in Atom.
```fish
function foo
if not string length $argv
echo "I got nothing."
end
end
```
Screenshot from Atom showing the desired effect:
Screenshot of Vim before my change. Note that the `end` doesn't match the `if`. This made my eye twitch. 
Screenshot of Vim AFTER my change. It doesn't match Atom completely, but that's largely due to the [vim-fish](https://github.com/dag/vim-fish) plugin I'm using for syntax. At least …
> Add a tweak for fish shell scripts

- colors/onedark.vim
I added a fix for the status line in vim 8 builtin terminal. It now looks the same as the statusline.
I  could not find any other spots that needs changing, so I think it should be ready. This is my first PR, so lead me in the right direction if something is wrong!
All the best, and thanks for a nice scheme!
> Added terminal statusbar highlight group

- colors/onedark.vim
Now the optional setting for the tildes seem to work. I'll gladly add a notice in the README if you want!
If a user sets `let g:onedark_hide_endofbuffer=1` in vimrc then the tildes are removed. Otherwise, keep vim as vim!
:)
> Added optional setting for end of buffer tildes

- colors/onedark.vim
Some changes to make onedark more like Atom with Go.
Before - After picture
init.vim if it helps
```
call plug#begin()
" General plugins
Plug 'joshdick/onedark.vim'
Plug 'sheerun/vim-polyglot'
call plug#end()
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_variable_declarations = 1
let g:go_highlight_variable_assignments = 1
let g:go_highlight_types = 1
set termguicolors
set background=dark
color onedark
```
> Add specifics highlights for Go

- colors/onedark.vim
Dear maintainers,
Hi!
I modified the `colors/onedark.vim` file so that the paired parentheses in terminal look the same as in GUI, that is to say, underline.
Regards,
Yu
> parentheses in terminal the same as in gui

- colors/onedark.vim
`SpecialChar` currently has no highlighting (cause of #222), but the majority of
other existing `Special` characters in the theme are highlighted as
dark yellow (`htmlSpecialChar`, `texSpecialChar`.)
So, add dark yellow highlighting for `SpecialChar` and change
`perlSpecialString` accordingly, so special characters are highlighted
consistently across all languages.
Resolves #222.
Closes #237.
> Consistent highlighting for special characters

- colors/onedark.vim
Neovim v0.5 will soon ship with a LSP client. They recently have added highlights for diagnostic messages from LSP servers, see [:lsp-highlight](https://github.com/neovim/neovim/blob/08c0eef52a31f70190fd4aa0ea8d54c0a169b284/runtime/doc/lsp.txt#L376). This pull request adds support for them.
I didn't add lines for `LspDiagnosticsVirtual*`, `LspDiagnosticsSigns*` and `LspDiagnosticsHint*` highlights since the they are linked to their corresponding `LspDiagnosticsDefault` by default as the doc mentions.
> Add support for Neovim LSP

- colors/onedark.vim
Fixes #220
Create a copy of color dictionary and apply changes to it instead of the original.
Currently, calling `extend_highlight()` will overwrite scheme-defined color dictionaries under the following conditions:
1. Call `extend_highlight()` on a Highlight Group and pass new values for a property (`"fg"` or `"bg"`)
2. The passed property (`"fg"` or `"bg"`) for that Highlight Group was previously assigned a scheme-defined color dictionary
Examples of how this causes unexpected behavior:
User calls `onedark#extend_highlight('Normal', {'bg': {'gui': 'NONE'}})` in order to have a transparent background.
`s:group_colors["Normal"].bg` was previously assigned `s:black` [in](https://github.com/joshdick/onedark.vim/blob/94ff495eac89cea2532d8e0022f67c79a24d9649/colors/onedark.vim#L86-L87) `s:h()` …
> Do not overwrite scheme-wide colors with extend_highlight

- colors/onedark.vim
> feat(plugin): Add support for lewis6991/gitsigns.nvim

- colors/onedark.vim
Highlight groups for Neovim LSP have changed in version 0.5.1 (nightly/master), see [this post](https://github.com/neovim/neovim/issues/14090#issuecomment-921312955). This PR updates them without breaking backward compatibility. The `LspDiagnosticsVirtualText*` groups have been removed so that they are the same as the defaults, otherwise the background is not correct:
> Update Neovim LSP colors

- colors/onedark.vim
Support `CocFadeOut` and by extension `CocUnusedHighlight` for highlighting unnecessary code.
Uses `special_grey`, looks like:
> feat: support CocFadeOut

- colors/onedark.vim
this fixes what looks like a simple oversight.  The `gui` attr-list is copied over in calls to `onedark#extend_highlight`, but not `cterm`.
> fix: allow extend_highlight to set cterm attr-list
